#!/bin/bash

# ADD dependency scripts
. scripts/script_log_color.sh

# GLOBAL variables
REGISTRY="docker.io/amizzuddin"
COMPOSES_DIRECTORY="composes"
COMMAND_OUTPUT_FILE="command_output.log"

get_image_and_tag_name(){
    VERSION=$(get_latest_version_id)
    REPOSITORY=$(basename -s .git `git config --get remote.origin.url`)
    if [ $TARGET == "PROD" ]; then
        IMAGE_TARGET=${PRODUCTION_TARGET,,} # lowercase
        IMAGE="${REPOSITORY}_${IMAGE_TARGET}"
    else
        IMAGE_TARGET=${TARGET,,} # lowercase
        IMAGE="${REPOSITORY}_${IMAGE_TARGET}"
    fi
    IMAGE_TAG="${IMAGE}:${VERSION}"
    IMAGE_TAG_LATEST="${IMAGE}:latest"
    REGISTRY_IMAGE="${REGISTRY}/${IMAGE_TAG}"
    REGISTRY_IMAGE_LATEST="${REGISTRY}/${IMAGE_TAG_LATEST}"
}

get_compose_file_name(){
    TEST_COMPOSE_FILE="prod_compose.yml"
    if [ $TARGET = "DEV" ];
    then
        TEST_COMPOSE_FILE="coverage_compose.yml"
    fi
}

get_latest_version_id(){
    VERSION_FILE=VERSION

    if [ ! -f "$VERSION_FILE" ]; then
        echo "VERSION FILE NOT FOUND!!!!"
        exit
    fi

    local LATEST_VERSION_LOG="UNKNOWN"
    read -r LATEST_VERSION_LOG<$VERSION_FILE
    echo "Latest log from VERSION file: $LATEST_VERSION_LOG" >&2 # Print messager to stderr

    VERSION_ID=$(echo $LATEST_VERSION_LOG | cut -d' ' -f1)
    echo $VERSION_ID
}

print_help() {
    echo -e "\nUsage:"
    echo -e "  $1 ${YELLOW}[command] [target] [production_target]${NO_COLOR}\n"
    echo -e "Available ${YELLOW}[command]${NO_COLOR}:"
    echo -e "  ${CYAN}init${NO_COLOR}           Generate files required for development/deployment"
    echo -e "  ${CYAN}build${NO_COLOR}          Build container image"
    echo -e "  ${CYAN}push${NO_COLOR}           Push to registry"
    echo -e "  ${CYAN}pull${NO_COLOR}           Pull from registry"
    echo -e "  ${CYAN}test${NO_COLOR}           Test Pull/Build image"
    echo -e "  ${CYAN}terminate${NO_COLOR}      Terminate running test image"
    echo -e "Available ${YELLOW}[target]${NO_COLOR}"
    echo -e "  ${CYAN}dev${NO_COLOR}            Devcontainer"
    echo -e "  ${CYAN}prod${NO_COLOR}           Production"
    echo -e "Available ${YELLOW}[production_target]${NO_COLOR}"
    echo -e "  ${CYAN}assignment_1${NO_COLOR}   Assignment 1"
    echo -e "  ${CYAN}assignment_2${NO_COLOR}   Assignment 2"
    echo -e "  ${CYAN}project${NO_COLOR}        Project"
    exit 1
}

check_argument() {
    RUN=$1
    COMMAND=${2^^}              # Convert to uppercase
    TARGET=${3^^}               # Convert to uppercase
    PRODUCTION_TARGET=${4^^}    # Convert to uppercase
    check_command
}

check_command() {
    if [ -z ${COMMAND} ]; then
        echo -e "${RED}ERROR! Please specify 'command'${NO_COLOR}"
        print_help $RUN
    fi

    if [ -z ${TARGET} ]; then
        echo -e "${RED}ERROR! Please specify 'target'${NO_COLOR}"
        print_help $RUN
    fi
    if [[ ! ${TARGET} =~ ^(DEV|PROD)$ ]]; then
        echo -e "${RED}ERROR! Unknown target: ${TARGET}${NO_COLOR}"
        print_help $RUN
    fi

    if [ ${TARGET} == "PROD" ]; then
        if [ -z ${PRODUCTION_TARGET} ]; then
            echo -e "${RED}ERROR! Please specify 'production_target' for production target${NO_COLOR}"
            print_help $RUN
        fi
        if [[ ! ${PRODUCTION_TARGET} =~ ^(ASSIGNMENT_1|ASSIGNMENT_2|PROJECT)$ ]]; then
            echo -e "${RED}ERROR! Unknown production_target: ${PRODUCTION_TARGET}${NO_COLOR}"
            print_help $RUN
        fi
        TARGET=$PRODUCTION_TARGET
    fi

    case $COMMAND in
        INIT)
            COMMAND_FUNCTION=""
            # To ensure `execute_command()` does not process `init_command`
            # since all commands requires to invoke `init_command`
            ;;
        BUILD)
            COMMAND_FUNCTION="build_command"
            ;;
        PUSH)
            COMMAND_FUNCTION="push_command"
            ;;
        PULL)
            COMMAND_FUNCTION="pull_command"
            ;;
        TEST)
            COMMAND_FUNCTION="test_command"
            ;;
        TERMINATE)
            COMMAND_FUNCTION="terminate_command"
            ;;
        *)
            print_help $RUN
            ;;
    esac

    # initialize workspace only when COMMAND and TARGET is valid
    init_command
}

execute_command(){
    # Exit when command is empty, example `init_command` has COMMAND_CUNTION=""
    if [ -z ${COMMAND_FUNCTION} ]; then
        exit
    fi
    $func $COMMAND_FUNCTION
}

init_command(){
    echo -e "Initialized workspace for development"
    get_image_and_tag_name
    get_compose_file_name
    generate_env_file
    echo -e "${GREEN}Initialized workspace completed${NO_COLOR}"
}

generate_env_file(){
    echo -e "Generate .env file at '${COMPOSES_DIRECTORY}' directory"
    touch ${COMPOSES_DIRECTORY}/.env

    declare -A ENVIRONMENTS_VARIABLES
    ENVIRONMENTS_VARIABLES["TARGET"]=${TARGET}
    ENVIRONMENTS_VARIABLES["REPOSITORY"]=${REPOSITORY}
    ENVIRONMENTS_VARIABLES["REGISTRY"]=${REGISTRY}
    ENVIRONMENTS_VARIABLES["TAG"]=${VERSION}
    ENVIRONMENTS_VARIABLES["IMAGE"]=${IMAGE}
    ENVIRONMENTS_VARIABLES["IMAGE_TAG"]=${IMAGE_TAG}
    ENVIRONMENTS_VARIABLES["IMAGE_TAG_LATEST"]=${IMAGE_TAG_LATEST}
    ENVIRONMENTS_VARIABLES["REGISTRY_IMAGE"]=${REGISTRY_IMAGE}
    ENVIRONMENTS_VARIABLES["REGISTRY_IMAGE_LATEST"]=${REGISTRY_IMAGE_LATEST}

    local LOOP_COUNTER=0
    for KEY in "${!ENVIRONMENTS_VARIABLES[@]}";
    do
        if [ $LOOP_COUNTER -eq 0 ]; then
            # Ensure contents in ${COMPOSES}/.env is overwritten
            echo "export ${KEY}=${ENVIRONMENTS_VARIABLES[$KEY]}" > $COMPOSES_DIRECTORY/.env
        else
            echo "export ${KEY}=${ENVIRONMENTS_VARIABLES[$KEY]}" >> $COMPOSES_DIRECTORY/.env
        fi

        if [  $? -ne 0 ]; then
            echo -e "${RED}Error overwriting environment '$KEY:${OVERWRITE_ENVIRONMENTS[$KEY]}'${NO_COLOR}"
            exit 1
        fi
        ((LOOP_COUNTER++))
    done
}

build_command() {
    local BUILD_COMMAND="docker-compose --file ${COMPOSES_DIRECTORY}/build_compose.yml build construction"
    execute_and_validate_docker_compose_command $BUILD_COMMAND

    docker tag ${REGISTRY_IMAGE} ${REGISTRY_IMAGE_LATEST}
    if [  $? -ne 0 ]; then
        echo -e "${RED}Failed to retag '${COMPONENT}' image ${NO_COLOR}"
    fi

    docker tag ${REGISTRY_IMAGE} ${IMAGE_TAG_LATEST}
    if [  $? -ne 0 ]; then
        echo -e "${RED}Failed to retag '${COMPONENT}' image ${NO_COLOR}"
    fi
}

docker_login(){
    # Login via docker desktop for wsl2, Needed testing for linux machine
    echo -e "${BLUE}Attempt to login to Docker Registry${NO_COLOR}"
    docker login --username $DOCKER_USER --password-stdin $DOCKER_USER_TOKEN
    echo -e "${GREEN}Login Successful${NO_COLOR}"
}

push_command() {
    local PUSH_COMMAND="docker-compose --file ${COMPOSES_DIRECTORY}/build_compose.yml push"
    execute_and_validate_docker_compose_command $PUSH_COMMAND
}

pull_command() {
    local PULL_COMMAND="docker-compose --file ${COMPOSES_DIRECTORY}/build_compose.yml pull"
    execute_and_validate_docker_compose_command $PULL_COMMAND

    docker tag ${REGISTRY_IMAGE} ${IMAGE_TAG}
    if [  $? -ne 0 ]; then
        echo -e "${RED}Failed to retag '${COMPONENT}' image ${NO_COLOR}"
    fi

    docker tag ${REGISTRY_IMAGE_LATEST} ${IMAGE_TAG_LATEST}
    if [  $? -ne 0 ]; then
        echo -e "${RED}Failed to retag '${COMPONENT}' image ${NO_COLOR}"
    fi
}

test_command() {
    if [ -z "$(docker images -q $REGISTRY_IMAGE 2> /dev/null)" ];
    then
        echo -e "${ORANGE}Image $REGISTRY_IMAGE not found${NO_COLOR}"
        pull_command
    fi

    local TEST_COMMAND="docker-compose --file ${COMPOSES_DIRECTORY}/${TEST_COMPOSE_FILE} up"
    execute_and_validate_docker_compose_command $TEST_COMMAND
}

terminate_command() {
    if [ -z "$(docker ps -a --filter "name=${IMAGE}" --format "{{.Image}}" 2> /dev/null)" ];
    then
        echo -e "${ORANGE}No running container with image: '$IMAGE' not found${NO_COLOR}"
    else
        local TERMINATE_COMMAND="docker-compose --file ${COMPOSES_DIRECTORY}/${TEST_COMPOSE_FILE} down"
        execute_and_validate_docker_compose_command $TERMINATE_COMMAND
    fi
}

execute_and_validate_docker_compose_command(){
    local DOCKER_COMPOSE_COMMAND=$@

    echo -e "Executing '${DOCKER_COMPOSE_COMMAND}'"

    # Execute compose command and write to a temp file
    eval $DOCKER_COMPOSE_COMMAND
    if [ $? != 0 ]; then
        echo -e "${RED}Failed to execute the command '${DOCKER_COMPOSE_COMMAND}' for '${IMAGE}' image${NO_COLOR}"
        exit 1
    fi

    echo -e "${GREEN}${COMMAND}ing completed successfully!${NO_COLOR}"
}

check_argument $0 $1 $2 $3
execute_command
