services:

  construction:
    build:
      context: ..
      dockerfile: Dockerfile
      target: ${TARGET}
      args:
        IMAGE: ${IMAGE}
        REPOSITORY: ${REPOSITORY}
    image: ${REGISTRY_IMAGE}
