services:

  assignment_1:
    extends:
      file: common_compose.yml
      service: common_service
    image: amizzuddin/sc4052_assignment_1:latest
    container_name: assignment_1
    ports:
      - "8050:8050"

  assignment_2:
    image: amizzuddin/sc4052_assignment_2:latest
    container_name: assignment_2
    ports:
      - "8050:8050"

  project:
    extends:
      file: common_compose.yml
      service: common_service
    image: amizzuddin/project:latest
    container_name: project
